#define ERR_EXTRN_TO_PROTO 0x00
#define ERR_NAME_SYNTAX_ERR 0x01
#define ERR_ACC_CTRL_VLTN 0x02
#define ERR_ABORT 0x03
#define ERR_ALLC_SIZE_TOO_BIG 0x04
#define ERR_ALLC_SIZE_TOO_SMALL 0x05
#define ERR_TRNSCT_ORDR 0x06
#define ERR_OP_NOT_IMPL 0x07
#define ERR_FILE_NOT_FOUND 0x08
#define ERR_TO_FOLLOW 0x09

#define CHNG_DATA_ITENT 0x00
#define RETR_RQST 0x01
#define STORE_REQUEST 0x02
#define 
